/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/model.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.597, 0]} scale={0.843}>
        <mesh geometry={nodes.Roundcube003_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Roundcube003_2.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.gltf')
